Select FILE# as "File#"
	, NAME as "Employee"
	,CHECKVIEWEARNSAMT as "H&W"
	, CHECKVIEWGROSSPAYA as "Gross"
	, CHECKVIEWNETPAYAMT as "Net"
	, CHECKVIEWREGHOURS as "Hours"
	,TO_CHAR(CHECKVIEWPAYDATE,'MM/DD/YYYY') as "PayDate"
	,Cast(CHECKVIEWWEEK# as int) AS "PayWeek"

from V_CHK_VW_EARNINGS
WHERE CHECKVIEWYEAR# = 2013
AND CHECKVIEWEARNSCD IN ('W','2')
ORDER BY NAME,CHECKVIEWWEEK#