//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emailTotalHours {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class staticVariables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal staticVariables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("emailTotalHours.staticVariables", typeof(staticVariables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\iomega-nas\Public1\IT Department\Pinnacle\Database\Pinnacle.sqlite.
        /// </summary>
        internal static string dbPath {
            get {
                return ResourceManager.GetString("dbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Public1\IT Department\Pinnacle\fop.
        /// </summary>
        internal static string fopDirectory {
            get {
                return ResourceManager.GetString("fopDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Progra~1\HTC\fop.
        /// </summary>
        internal static string fopDirectory_Test {
            get {
                return ResourceManager.GetString("fopDirectory_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reports@htcorp.net.
        /// </summary>
        internal static string MailFrom {
            get {
                return ResourceManager.GetString("MailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kristenl@htcorp.net.
        /// </summary>
        internal static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\iomega-nas\Public1\Pinnacle Docs\Monthly Reports\Oneida County Reports.
        /// </summary>
        internal static string reportsDirectory {
            get {
                return ResourceManager.GetString("reportsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Public1\ITDEPA~1\Pinnacle\Reports\pinnacleOneidaCty.xsl.
        /// </summary>
        internal static string xslDirectory {
            get {
                return ResourceManager.GetString("xslDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\jeremyp.HTC\Documents\Development\Pinnacle\Reports\pinnacleOneidaCty.xsl.
        /// </summary>
        internal static string xslDirectory_Test {
            get {
                return ResourceManager.GetString("xslDirectory_Test", resourceCulture);
            }
        }
    }
}
