//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiTechnic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HiTecResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HiTecResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiTechnic.HiTecResources", typeof(HiTecResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\iomega-nas\Public1\IT Department\HiTechnic\DailyFinal.xls.
        /// </summary>
        public static string DailyOrders_XLS {
            get {
                return ResourceManager.GetString("DailyOrders_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\iomega-nas\Public1\IT Department\HiTechnic\Database\HiTechnic.sqlite.
        /// </summary>
        public static string DB {
            get {
                return ResourceManager.GetString("DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\fedex01dwyer\fedex\fedexE.csv.
        /// </summary>
        public static string FedExExpress {
            get {
                return ResourceManager.GetString("FedExExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\fedex01dwyer\fedex\fedexG.csv.
        /// </summary>
        public static string FedExGround {
            get {
                return ResourceManager.GetString("FedExGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\HTC\HiTechnic\PackingList\fop.
        /// </summary>
        public static string FOP_Directory {
            get {
                return ResourceManager.GetString("FOP_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Foxit Software\Foxit Reader.
        /// </summary>
        public static string FoxIt_Directory {
            get {
                return ResourceManager.GetString("FoxIt_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nancy@hitechnic.com.
        /// </summary>
        public static string HiTec_Email {
            get {
                return ResourceManager.GetString("HiTec_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shippingconfirmation@htcorp.net.
        /// </summary>
        public static string HTC_Email {
            get {
                return ResourceManager.GetString("HTC_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to susanm@htcorp.net.
        /// </summary>
        public static string HTC_EndOfDay {
            get {
                return ResourceManager.GetString("HTC_EndOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @/t &quot;%Temp%\PackingList.pdf&quot;.
        /// </summary>
        public static string PackingList_PrintString {
            get {
                return ResourceManager.GetString("PackingList_PrintString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\jeremyp.HTC\Documents\Development\Lego\SqLite\Test\DailyFinal.xls.
        /// </summary>
        public static string testDailyOrders_XLS {
            get {
                return ResourceManager.GetString("testDailyOrders_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\jeremyp.HTC\Documents\Development\Lego\SqLite\Test\HiTechnic_Test.sqlite.
        /// </summary>
        public static string testDB {
            get {
                return ResourceManager.GetString("testDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeremyp@htcorp.net.
        /// </summary>
        public static string testEmail {
            get {
                return ResourceManager.GetString("testEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\FedEx01Dwyer\fedex\epostage.xls.
        /// </summary>
        public static string USPS_XLS {
            get {
                return ResourceManager.GetString("USPS_XLS", resourceCulture);
            }
        }
    }
}
